import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useAppSelector } from '../redux/hook';
import { useGetPokemonByNameQuery } from '../services/freePostAPI';

export default function Home() {

  // const count = useSelector((state: AppState) => state.counter.value)
  // const users = useAppSelector(state=>console.log(state));
  const { data, error, isLoading } = useGetPokemonByNameQuery('bulbasaur')
  console.log(data,isLoading)
  // console.log(users);
  if(isLoading){
   return <h1>Loading</h1>
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div>
      <h1> This Is Main Page </h1>
  {data.map(e=><h1>{e.name}</h1>)}
     
       </div>
      </main>
    </>
  )
}
